### PR TITLE
Add Tokyo campus

### PR DESCRIPTION
**Pull request by masakiva**
**Describe the pull request**

Added the Tokyo campus information following the tutorial on https://github.com/42atomys/stud42/wiki/Contributions

**Checklist**

I didn't manage to open the application in my Browser to see the changes (localhost:3000 keeps loading without displaying anything)
Also, I'm sorry, I don't know how to run the linter...

link to the issue #347

### CODE REVIEW

**Comment by 42atomys** [comment]
Hello @masakiva,

Thanks for your first contribution 🎉 
your follow is great, for your problem on run the project, the installation is explain step by step on : https://github.com/42Atomys/stud42/blob/main/CONTRIBUTING.md ? 

FYI: Formating the interface can be run under vscode tasks : `>Run Tasks >Format interface` or with `yarn make-pretty`. But actually your work pass the linter and test so no formatting is needed, congratulations 🎉 

---
The last step I need to handle before merge is to valid with a staff member of 42 Tokyo (this is for data protection and data process law in France).

**Comment by masakiva** [comment]
Thank you for your kind reply, and for the explanations.
I asked the staff, I will come back when I will get a response!

**Comment by masakiva** [comment]
The staff is OK for merging, I gave them your email adress (contact@atomys.fr), you should receive an email soon!

**Review by 42atomys — APPROVED** [review]

**Comment by masakiva** [comment]
@42atomys Thank you for the small fix, and for the merge! I look forward to using the new version with my campusmates soon!!

**Pull request merged**
