### PR TITLE
feat: adding mulhouse campus

### PR DESCRIPTION
**Pull request by TheFoxan12**
**Describe the pull request**

I added the campus of Mulhouse following the way other campuses were implemented.
I created a ts file for Mulhouse campus, added mulhouse to index.ts, added mulhouse in types.d.ts.

**Checklist**

- [x] I have made the modifications or added tests related to my PR
- [x] I have run the tests and linters locally and they pass
- [x] I have added/updated the documentation for my RP

**Additional context**

Nothing

### CODE REVIEW

**Comment by 42atomys** [comment]
Thanks for your venue and your first contribution @TheFoxan12 🎉 

Your code pass the Linters correctly, I start the discussion with the staff of your campus to allow us to integrate it. When that will be accepted, I processed to the merge and you will be pinged in the release including your contribution 🥇

**Comment by TheFoxan12** [comment]
> Thanks for your venue and your first contribution @TheFoxan12 🎉
> 
> Your code pass the Linters correctly, I start the discussion with the staff of your campus to allow us to integrate it. When that will be accepted, I processed to the merge and you will be pinged in the release including your contribution 🥇

**Comment by TheFoxan12** [comment]
oops

**Comment by TheFoxan12** [comment]
Sorry !

> Thanks for your venue and your first contribution @TheFoxan12 🎉
> 
> Your code pass the Linters correctly, I start the discussion with the staff of your campus to allow us to integrate it. When that will be accepted, I processed to the merge and you will be pinged in the release including your contribution 🥇

Thanks !

**Review by 42atomys — APPROVED** [review]
LGTM, I will just update the T: element to be in each side of the row. 

Staff approved the request, campus map will be included in the next release 🎉

**Pull request merged**
