### PR TITLE
feat(cluster): integrate 42 urduliz campus

### PR DESCRIPTION
**Pull request by samuelcordero**
**Describe the pull request**

Added 42 Urduliz cluster map integration

**Checklist**

- [*] I have made the modifications or added tests related to my PR
- [*] I have run the tests and linters locally and they pass
- [*] I have added/updated the documentation for my RP

**Additional context**

### CODE REVIEW

**Review by samuelcordero — COMMENTED** [review]
Corrected indent

**Comment by 42atomys** [comment]
Hi @samuelcordero 

Firstly, thank you for taking the time to contribute to S42! 🎉
✅ I've reviewed your pull request and I'm pleased to say that it looks great and has been approved.

🕐 I need to check the interface and I dont have my laptop in hand currently. I'll keep the pull request open and will merge it as soon as I reviewed.

Once again, thanks for your contribution, and please feel free to reach me and others contributors on the [Discord](https://discord.gg/5f864c6hyj) if you have any questions or if there's anything else you'd like to discuss 😄

**Comment by 42atomys** [comment]
Hi @samuelcordero 

Firstly, thank you for taking the time to contribute to S42! 🎉
⚠️ The CI failed in linting can you fix it please ? (`yarn make-pretty` will do the job)

🕐 I need to check the interface and I dont have my laptop in hand currently. I'll keep the pull request open and will merge it as soon as I reviewed.

Once again, thanks for your contribution, and please feel free to reach me and others contributors on the [Discord](https://discord.gg/5f864c6hyj) if you have any questions or if there's anything else you'd like to discuss 😄

**Comment by samuelcordero** [comment]
Hi @42atomys,
Thank you for everything! I hope it is okay now, linting reported 0 problems, 0 warnings. I'll be joining the discord, I'd love to be in touch with everyone involved. Have a nice day!

**Review by 42atomys — APPROVED** [review]
LGTM 🎉 
Thanks for your first contribution again, this will be released soon !

**Pull request merged**
